dataset:
  vis:
  - name: hypersim_depth
    disp_name: hypersim_depth_vis
    dir: raw_hypersim/processed/val
    filenames: /home/shania/Marigold/data_split/hypersim_depth/selected_vis_sample.txt
    resize_to_hw:
    - 480
    - 640
